name: Simple Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previus Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-18.04
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-dpth: 0 #last commit
      # - uses: actions/setup-node@v2
      #   with:
      #     cache: 'npm'
      #     node-version: '14'
      # - name: Install dependencies
      #   run: npm ci
      - name: Lint
        # run: npm run eslint
        run: echo "running eslint pending"

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-dpth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  # to decrease the time
  # test:
  #   needs: [lint, build]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-dpth: 0
  #     - uses: actions/setup-node@v2
  #       with:
  #         cache: 'npm'
  #         node-version: '14'
  #     - name: Install dependencies
  #       run: npm ci
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: build
  #         path: build
  #     - name: Test
  #       run: npm test

  deploy:
    needs: [build] # [test, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build"
          production-branch: main
          github-token: ${{ github.token }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
